// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
#![allow(non_snake_case)]

use chrono::NaiveDateTime;
use diesel::prelude::*;
use diesel_derive_enum::DbEnum;

use crate::core::database::schema::users;

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "meetings_status_enum"]
pub enum MeetingsStatusEnum {
    Scheduled,
    Ongoing,
    Ended,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "members_role_enum"]
pub enum MembersRoleEnum {
    Admin,
    Member,
    Guest,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "members_status_enum"]
pub enum MembersStatusEnum {
    Active,
    Inactive,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "messages_type_enum"]
pub enum MessagesTypeEnum {
    Text,
    Image,
    Video,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "messages_status_enum"]
pub enum MessagesStatusEnum {
    Sent,
    Delivered,
    Read,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "records_status_enum"]
pub enum RecordsStatusEnum {
    Processing,
    Completed,
    Failed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[DieselType = "participants_status_enum"]
pub enum ParticipantsStatusEnum {
    Active,
    Inactive,
}

#[derive(Queryable, Debug)]
pub struct Ccu {
    pub id: i32,
    pub socketId: String,
    pub podName: String,
    pub createdAt: NaiveDateTime,
    pub userId: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Meeting {
    pub id: i32,
    pub title: String,
    pub password: String,
    pub avatar: Option<String>,
    pub status: MeetingsStatusEnum,
    pub latestMessageCreatedAt: Option<NaiveDateTime>,
    pub code: i32,
    pub createdAt: NaiveDateTime,
    pub updatedAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub latestMessageId: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Member {
    pub id: i32,
    pub role: MembersRoleEnum,
    pub status: MembersStatusEnum,
    pub createdAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub softDeletedAt: Option<NaiveDateTime>,
    pub userId: Option<i32>,
    pub meetingId: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Message {
    pub id: i32,
    pub data: String,
    pub type_: MessagesTypeEnum,
    pub status: MessagesStatusEnum,
    pub createdAt: NaiveDateTime,
    pub updatedAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub createdById: Option<i32>,
    pub meetingId: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Participant {
    pub id: i32,
    pub status: ParticipantsStatusEnum,
    pub createdAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub userId: Option<i32>,
    pub meetingId: Option<i32>,
    pub ccuId: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct RecordTrack {
    pub id: i32,
    pub urlToVideo: String,
    pub startTime: String,
    pub endTime: String,
    pub createdAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub recordId: Option<i32>,
    pub userId: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Record {
    pub id: i32,
    pub urlToVideo: Option<String>,
    pub thumbnail: Option<String>,
    pub duration: i32,
    pub status: RecordsStatusEnum,
    pub createdAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub meetingId: Option<i32>,
    pub createdById: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Session {
    pub id: i32,
    pub createdAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub userId: Option<i32>,
}

#[derive(Queryable, Selectable, Debug)]
#[diesel(table_name = users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct User {
    pub id: i32,
    pub fullName: Option<String>,
    pub userName: String,
    pub bio: Option<String>,
    pub googleId: Option<String>,
    pub githubId: Option<String>,
    pub appleId: Option<String>,
    pub avatar: Option<String>,
    pub createdAt: NaiveDateTime,
    pub updatedAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub lastSeenAt: Option<NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = users)]
pub struct NewUser<'a> {
    pub fullName: Option<&'a str>,
    pub userName: &'a str,
    pub bio: Option<&'a str>,
    pub googleId: Option<&'a str>,
    pub githubId: Option<&'a str>,
    pub appleId: Option<&'a str>,
    pub avatar: Option<&'a str>,
    pub createdAt: NaiveDateTime,
    pub updatedAt: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct WhiteBoard {
    pub id: i32,
    pub paints: String,
    pub createdAt: NaiveDateTime,
    pub deletedAt: Option<NaiveDateTime>,
    pub meetingId: Option<i32>,
}
