[package]
name = "waterbus-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "*", features = [
    "tower-compat",
    "oapi",
    "affix-state",
    "jwt-auth",
    "logging",
] }
serde = "1.0.219"
socketioxide = { version = "0.16.2", features = ["extensions", "state"] }
socketioxide-redis = "0.2.1"
tokio = "1.44.1"
tower = { version = "0.5.0", default-features = false }
tower-http = { version = "0.6.2", features = ["cors", "fs", "auth"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
chrono = "0.4.40"
diesel = { version = "2.2.8", features = ["postgres", "r2d2", "chrono"] }
diesel-derive-enum = "2.1.0"
dotenvy = "0.15.7"
time = "0.3.41"
jsonwebtoken = "9.3.1"
anyhow = "1.0.97"
