// Generated by diesel_ext

#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::prelude::*;
use salvo::oapi::ToSchema;
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::{core::database::schema::*, impl_from_i16_with_default};

fn default_room_type() -> i16 {
    0
}

fn default_streaming_protocol() -> i16 {
    0
}

#[repr(i16)]
#[derive(Debug, Clone, Copy, Serialize_repr, Deserialize_repr, ToSchema)]
#[salvo(schema(default = default_room_type, example = 0))]
pub enum RoomType {
    Conferencing = 0,
    LiveStreaming = 1,
}

impl_from_i16_with_default!(RoomType {
    Conferencing = 0,
    LiveStreaming = 1,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy, Serialize_repr, Deserialize_repr, ToSchema)]
#[salvo(schema(default = default_streaming_protocol, example = 0))]
pub enum StreamingProtocol {
    SFU = 0,
    HLS = 1,
    MOQ = 2,
}

impl_from_i16_with_default!(StreamingProtocol {
    SFU = 0,
    HLS = 1,
    MOQ = 2,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy)]
pub enum MembersRoleEnum {
    Owner = 0,
    Attendee = 1,
}
impl_from_i16_with_default!(MembersRoleEnum {
    Owner = 0,
    Attendee = 1,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy)]
pub enum MessagesTypeEnum {
    Default = 0,
    System = 1,
}
impl_from_i16_with_default!(MessagesTypeEnum {
    Default = 0,
    System = 1,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy)]
pub enum MessagesStatusEnum {
    Active = 0,
    Inactive = 1,
}
impl_from_i16_with_default!(MessagesStatusEnum {
    Active = 0,
    Inactive = 1,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy)]
pub enum RecordsStatusEnum {
    Recording = 0,
    Processing = 1,
    Finish = 2,
}
impl_from_i16_with_default!(RecordsStatusEnum {
    Recording = 0,
    Processing = 1,
    Finish = 2,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy)]
pub enum ParticipantsStatusEnum {
    Active = 0,
    Inactive = 1,
}
impl_from_i16_with_default!(ParticipantsStatusEnum {
    Active = 0,
    Inactive = 1,
});

#[repr(i16)]
#[derive(Debug, Clone, Copy)]
pub enum RoomStatusEnum {
    Active = 0,
    Inactive = 1,
}
impl_from_i16_with_default!(RoomStatusEnum {
    Active = 0,
    Inactive = 1,
});

impl TryFrom<i32> for RoomStatusEnum {
    type Error = ();

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(RoomStatusEnum::Active),
            1 => Ok(RoomStatusEnum::Inactive),
            _ => Err(()),
        }
    }
}

#[derive(
    Queryable,
    Selectable,
    Debug,
    Clone,
    Serialize,
    Deserialize,
    QueryableByName,
    Identifiable,
    ToSchema,
)]
#[diesel(table_name = rooms)]
#[serde(rename_all = "camelCase")]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Room {
    pub id: i32,
    pub title: String,
    #[serde(skip_serializing)]
    pub password: Option<String>,
    pub avatar: Option<String>,
    pub status: i16,
    pub latest_message_created_at: Option<NaiveDateTime>,
    pub code: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
    pub latest_message_id: Option<i32>,
    pub type_: i16,
    pub capacity: Option<i32>,
    pub streaming_protocol: Option<i16>,
}

#[derive(
    Queryable,
    Selectable,
    Debug,
    Clone,
    Serialize,
    Deserialize,
    QueryableByName,
    Associations,
    Identifiable,
    ToSchema,
)]
#[diesel(table_name = members)]
#[diesel(belongs_to(Room))]
#[diesel(belongs_to(User))]
#[serde(rename_all = "camelCase")]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[salvo(schema(example = json!({"id": 1, "role": 0, "created_at": "2021-01-01T00:00:00Z", "deleted_at": null, "soft_deleted_at": null, "user_id": 1, "room_id": 1})))]
pub struct Member {
    pub id: i32,
    pub role: i16,
    pub created_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
    pub soft_deleted_at: Option<NaiveDateTime>,
    pub user_id: i32,
    pub room_id: i32,
}

#[derive(
    Queryable,
    Selectable,
    Debug,
    Clone,
    Serialize,
    Deserialize,
    QueryableByName,
    Associations,
    Identifiable,
    ToSchema,
)]
#[diesel(table_name = messages)]
#[diesel(belongs_to(Room, foreign_key = room_id))]
#[diesel(belongs_to(User, foreign_key = created_by_id))]
#[serde(rename_all = "camelCase")]
#[diesel(primary_key(id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Message {
    pub id: i32,
    pub data: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by_id: i32,
    pub room_id: i32,
    pub type_: i16,
    pub status: i16,
}

#[derive(
    Queryable,
    Selectable,
    Debug,
    Clone,
    Serialize,
    Deserialize,
    QueryableByName,
    Associations,
    Identifiable,
    ToSchema,
)]
#[diesel(table_name = participants)]
#[serde(rename_all = "camelCase")]
#[diesel(belongs_to(Room))]
#[diesel(belongs_to(User))]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[salvo(schema(example = json!({"id": 1, "created_at": "2021-01-01T00:00:00Z", "deleted_at": null, "user_id": 1, "room_id": 1, "status": 0, "node_id": null})))]
pub struct Participant {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
    pub user_id: i32,
    pub room_id: i32,
    pub status: i16,
    #[serde(skip_serializing)]
    pub node_id: Option<String>,
}

#[derive(
    Queryable,
    Selectable,
    Debug,
    Clone,
    Serialize,
    Deserialize,
    QueryableByName,
    Identifiable,
    ToSchema,
)]
#[diesel(table_name = users)]
#[serde(rename_all = "camelCase")]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[salvo(schema(example = json!({"id": 1, "full_name": "John Doe", "user_name": "john_doe", "bio": "I am a software engineer", "external_id": "123123", "avatar": "https://example.com/avatar.png", "created_at": "2021-01-01T00:00:00Z", "updated_at": "2021-01-01T00:00:00Z", "deleted_at": null, "last_seen_at": null})))]
pub struct User {
    pub id: i32,
    pub full_name: Option<String>,
    pub user_name: String,
    pub bio: Option<String>,
    pub external_id: String,
    pub avatar: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub deleted_at: Option<NaiveDateTime>,
    pub last_seen_at: Option<NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = users)]
pub struct NewUser<'a> {
    pub full_name: Option<&'a str>,
    pub user_name: &'a str,
    pub bio: Option<&'a str>,
    pub external_id: &'a str,
    pub avatar: Option<&'a str>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Insertable)]
#[diesel(table_name = messages)]
pub struct NewMessage<'a> {
    pub data: &'a str,
    pub created_by_id: Option<&'a i32>,
    pub room_id: Option<&'a i32>,
    pub status: &'a i16,
    pub type_: &'a i16,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Insertable)]
#[diesel(table_name = rooms)]
pub struct NewRoom<'a> {
    pub title: &'a str,
    pub password: Option<&'a str>,
    pub code: &'a str,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub latest_message_created_at: NaiveDateTime,
    pub status: i16,
    pub type_: i16,
    pub capacity: Option<i32>,
    pub streaming_protocol: Option<i16>,
}

#[derive(Insertable)]
#[diesel(table_name = members)]
pub struct NewMember<'a> {
    pub room_id: &'a i32,
    pub created_at: NaiveDateTime,
    pub user_id: Option<i32>,
    pub role: i16,
}

#[derive(Insertable)]
#[diesel(table_name = participants)]
pub struct NewParticipant<'a> {
    pub room_id: &'a i32,
    pub user_id: Option<i32>,
    pub created_at: NaiveDateTime,
    pub status: i16,
}
