#[derive(Debug)]
pub enum SocketEvent {
    PublishCSS,
    PublishSSC,
    SubscribeCSS,
    AnswerSubscriberSSC,
    AnswerSubscriberCSS,
    PublisherCandidateCSS,
    PublisherCandidateSSC,
    SubscriberCandidateCSS,
    SubscriberCandidateSSC,
    LeaveRoomCSS,
    NewParticipantSSC,
    ParticipantHasLeftSSC,
    SetE2eeEnabledCSS,
    SetE2eeEnabledSSC,
    SetVideoEnabledCSS,
    SetVideoEnabledSSC,
    SetCameraTypeCSS,
    SetCameraTypeSSC,
    SetAudioEnabledCSS,
    SetAudioEnabledSSC,
    SetScreenSharingSSC,
    SetScreenSharingCSS,
    HandRaisingSSC,
    HandRaisingCSS,
    SubtitleSSC,
    SetSubscribeSubtitleCSS,
    StartRecordSSC,
    StopRecordSSC,
    PublisherRenegotiationCSS,
    PublisherRenegotiationSSC,
    SubscriberRenegotiationSSC,
    StartWhiteBoardSSC,
    StartWhiteBoardCSS,
    UpdateWhiteBoardCSS,
    UpdateWhiteBoardSSC,
    CleanWhiteBoardCSS,
    CleanWhiteBoardSSC,
    SendMessageSSC,
    UpdateMessageSSC,
    DeleteMessageSSC,
    NewMemberJoinedSSC,
    NewInvitationSSC,
    Connection,
    Disconnect,
    Destroy,
    SendPodNameSSC,
    ReconnectCSS,
}

impl SocketEvent {
    pub fn to_str(&self) -> &str {
        match self {
            SocketEvent::PublishCSS => "PUBLISH_CSS",
            SocketEvent::PublishSSC => "PUBLISH_SSC",
            SocketEvent::SubscribeCSS => "SUBSCRIBE_CSS",
            SocketEvent::AnswerSubscriberSSC => "SEND_SDP_SUBSCRIBER_SSC",
            SocketEvent::AnswerSubscriberCSS => "SEND_SDP_SUBSCRIBER_CSS",
            SocketEvent::PublisherCandidateCSS => "SEND_CANDIDATE_PUBLISHER_CSS",
            SocketEvent::PublisherCandidateSSC => "SEND_CANDIDATE_PUBLISHER_SSC",
            SocketEvent::SubscriberCandidateCSS => "SEND_CANDIDATE_SUBSCRIBER_CSS",
            SocketEvent::SubscriberCandidateSSC => "SEND_CANDIDATE_SUBSCRIBER_SSC",
            SocketEvent::LeaveRoomCSS => "LEAVE_ROOM_CSS",
            SocketEvent::NewParticipantSSC => "NEW_PARTICIPANT_SSC",
            SocketEvent::ParticipantHasLeftSSC => "PARTICIPANT_HAS_LEFT_SSC",
            SocketEvent::SetE2eeEnabledCSS => "SET_E2EE_ENABLED_CSS",
            SocketEvent::SetE2eeEnabledSSC => "SET_E2EE_ENABLED_SSC",
            SocketEvent::SetVideoEnabledCSS => "SET_VIDEO_ENABLED_CSS",
            SocketEvent::SetVideoEnabledSSC => "SET_VIDEO_ENABLED_SSC",
            SocketEvent::SetCameraTypeCSS => "SET_CAMERA_TYPE_CSS",
            SocketEvent::SetCameraTypeSSC => "SET_CAMERA_TYPE_SSC",
            SocketEvent::SetAudioEnabledCSS => "SET_AUDIO_ENABLED_CSS",
            SocketEvent::SetAudioEnabledSSC => "SET_AUDIO_ENABLED_SSC",
            SocketEvent::SetScreenSharingSSC => "SET_SCREEN_SHARING_SSC",
            SocketEvent::SetScreenSharingCSS => "SET_SCREEN_SHARING_CSS",
            SocketEvent::HandRaisingSSC => "HAND_RAISING_SSC",
            SocketEvent::HandRaisingCSS => "HAND_RAISING_CSS",
            SocketEvent::SubtitleSSC => "SUBTITLE_SSC",
            SocketEvent::SetSubscribeSubtitleCSS => "SET_SUBSCRIBE_SUBTITLE_CSS",
            SocketEvent::StartRecordSSC => "START_RECORD_SSC",
            SocketEvent::StopRecordSSC => "STOP_RECORD_SSC",
            SocketEvent::PublisherRenegotiationCSS => "PUBLISHER_RENEGOTIATION_CSS",
            SocketEvent::PublisherRenegotiationSSC => "PUBLISHER_RENEGOTIATION_SSC",
            SocketEvent::SubscriberRenegotiationSSC => "SUBSCRIBER_RENEGOTIATION_SSC",
            SocketEvent::StartWhiteBoardSSC => "START_WHITE_BOARD_SSC",
            SocketEvent::StartWhiteBoardCSS => "START_WHITE_BOARD_CSS",
            SocketEvent::UpdateWhiteBoardCSS => "UPDATE_WHITE_BOARD_CSS",
            SocketEvent::UpdateWhiteBoardSSC => "UPDATE_WHITE_BOARD_SSC",
            SocketEvent::CleanWhiteBoardCSS => "CLEAN_WHITE_BOARD_CSS",
            SocketEvent::CleanWhiteBoardSSC => "CLEAN_WHITE_BOARD_SSC",
            SocketEvent::SendMessageSSC => "SEND_MESSAGE_SSC",
            SocketEvent::UpdateMessageSSC => "UPDATE_MESSAGE_SSC",
            SocketEvent::DeleteMessageSSC => "DELETE_MESSAGE_SSC",
            SocketEvent::NewMemberJoinedSSC => "NEW_MEMBER_JOINED_SSC",
            SocketEvent::NewInvitationSSC => "NEW_INVITATION_SSC",
            SocketEvent::SendPodNameSSC => "SEND_POD_NAME_SSC",
            SocketEvent::ReconnectCSS => "RECONNECT_CSS",
            SocketEvent::Connection => "connection",
            SocketEvent::Disconnect => "disconnect",
            SocketEvent::Destroy => "destroy",
        }
    }
}
