name: Rust CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  rust-check:
    name: Check Formatting & Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust (nightly)
        uses: actions/setup-rust@v1
        with:
          rust-version: nightly

      - name: Install clippy and rustfmt
        run: rustup component add clippy rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
